// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Padel.SGBD.Api.Data;

#nullable disable

namespace Padel.Sgbd.Api.Migrations
{
    [DbContext(typeof(PadelSGBDContext))]
    [Migration("20260814134011_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Padel.SGBD.Api.Model.Fermeture", b =>
                {
                    b.Property<int>("IdFermeture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFermeture"));

                    b.Property<DateOnly>("DateFermeture")
                        .HasColumnType("date");

                    b.Property<int?>("IdSite")
                        .HasColumnType("int");

                    b.HasKey("IdFermeture");

                    b.HasIndex("IdSite");

                    b.ToTable("Fermeture", (string)null);
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatch"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstPrive")
                        .HasColumnType("bit");

                    b.Property<int>("IdTerrain")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdMatch");

                    b.HasIndex("IdTerrain");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Membre", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DateFinPenalite")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdSiteRatt")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoldeDu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Matricule");

                    b.HasIndex("IdSiteRatt");

                    b.ToTable("Membre", null, t =>
                        {
                            t.HasCheckConstraint("CK_Membre_Type", "[Type] IN ('G', 'S', 'L')");
                        });
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Participations", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdMatch")
                        .HasColumnType("int");

                    b.Property<bool>("APaye")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstOrganisateur")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Matricule", "IdMatch");

                    b.HasIndex("IdMatch");

                    b.ToTable("Participation", (string)null);
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Site", b =>
                {
                    b.Property<int>("IdSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSite"));

                    b.Property<TimeOnly>("HFermeture")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HOuverture")
                        .HasColumnType("time");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSite");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Terrain", b =>
                {
                    b.Property<int>("IdTerrain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTerrain"));

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Terrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("nom_terrain");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("type");

                    b.HasKey("IdTerrain");

                    b.HasIndex("IdSite");

                    b.ToTable("Terrain", (string)null);
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Fermeture", b =>
                {
                    b.HasOne("Padel.SGBD.Api.Model.Site", "Site")
                        .WithMany()
                        .HasForeignKey("IdSite")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Match", b =>
                {
                    b.HasOne("Padel.SGBD.Api.Model.Terrain", "Terrain")
                        .WithMany()
                        .HasForeignKey("IdTerrain")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Membre", b =>
                {
                    b.HasOne("Padel.SGBD.Api.Model.Site", "Site")
                        .WithMany()
                        .HasForeignKey("IdSiteRatt");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Participations", b =>
                {
                    b.HasOne("Padel.SGBD.Api.Model.Match", "Match")
                        .WithMany("Participations")
                        .HasForeignKey("IdMatch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padel.SGBD.Api.Model.Membre", "Membre")
                        .WithMany("Participations")
                        .HasForeignKey("Matricule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Terrain", b =>
                {
                    b.HasOne("Padel.SGBD.Api.Model.Site", "Site")
                        .WithMany("Terrains")
                        .HasForeignKey("IdSite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Match", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Membre", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Padel.SGBD.Api.Model.Site", b =>
                {
                    b.Navigation("Terrains");
                });
#pragma warning restore 612, 618
        }
    }
}
